alias today='date +"%m-%d-%Y"'
alias path='echo -e ${PATH//:/\\n}'
alias root='sudo -i'
alias gitlg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias web='cd /var/www/html'
alias reboot='sudo shutdown -r now'
alias update='sudo apt update && sudo apt upgrade'
alias l.='ls -d .* --color=auto'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../..'
alias bc='bc -l'
alias diff='colordiff'
alias h='history'
alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias pscpu='ps auxf | sort -nr -k 3'
alias cpuinfo='lscpu'
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
alias rm='rm -I --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias itch.in='flatpak run io.itch.itch'
