alias today='date +"%m-%d-%Y"'
alias path='echo -e ${PATH//:/\\n}'
alias root='sudo -i'
alias gitlg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias web='cd /var/www/html'
alias reboot='sudo shutdown -r now'
alias update='sudo apt update && sudo apt upgrade'
alias l.='ls -d .* --color=auto'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../..'
alias diff='colordiff'
alias h='history'
alias psmem='ps auxf | sort -nr -k 4'
alias pscpu='ps auxf | sort -nr -k 3'
alias cpuinfo='lscpu'
alias rm='rm -r'
alias mv='mv -i'
alias cp='cp -r'
alias ln='ln -i'
alias weather='curl wttr.in/cleveland'
alias define='sdcv'
alias wifipass='nmcli dev wifi show-password'
alias ddg='w3m lite.duckduckgo.com'
alias itch.in='flatpak run io.itch.itch'
